export const categoryList = [
  {
    id: 1,
    name: "Beeld & Geluid",
    img: require("../assets/category_list/asset8.png"),
  },
  {
    id: 2,
    name: "Computers & Tablets",
    img: require("../assets/category_list/asset8.png"),
  },
  {
    id: 3,
    name: "Huishouden & Wonen",
    img: require("../assets/category_list/asset9.png"),
  },
  {
    id: 4,
    name: "Keuken",
    img: require("../assets/category_list/asset10.png"),
  },
  {
    id: 5,
    name: "Sport & Verzorging",
    img: require("../assets/category_list/asset11.png"),
  },
];

export const subCategoryList = [
  {
    id: 1,
    catId: 1,
    name: "Televisies",
    img: require("../assets/categoryItems/c1.jpeg"),
  },
  {
    id: 2,
    catId: 1,
    name: "Televisie accessoires",
    img: require("../assets/categoryItems/c2.jpeg"),
  },
  {
    id: 3,
    catId: 1,
    name: "Home cinema",
    img: require("../assets/categoryItems/c3.jpeg"),
  },
  {
    id: 4,
    catId: 1,
    name: "Speakers",
    img: require("../assets/categoryItems/c4.jpeg"),
  },

  {
    id: 5,
    catId: 2,
    name: "Televisies",
    img: require("../assets/categoryItems/c5.jpeg"),
  },
  {
    id: 6,
    catId: 2,
    name: "Televisie accessoires",
    img: require("../assets/categoryItems/c6.jpeg"),
  },
  {
    id: 7,
    catId: 2,
    name: "Home cinema",
    img: require("../assets/categoryItems/c7.jpeg"),
  },
  {
    id: 8,
    catId: 2,
    name: "Speakers",
    img: require("../assets/categoryItems/c8.jpeg"),
  },

  {
    id: 9,
    catId: 3,
    name: "Televisies",
    img: require("../assets/categoryItems/c13.jpeg"),
  },
  {
    id: 10,
    catId: 3,
    name: "Televisie accessoires",
    img: require("../assets/categoryItems/c9.png"),
  },
  {
    id: 11,
    catId: 3,
    name: "Home cinema",
    img: require("../assets/categoryItems/c11.jpeg"),
  },
  {
    id: 12,
    catId: 3,
    name: "Speakers",
    img: require("../assets/categoryItems/c12.jpeg"),
  },
];

export const productList = [
  {
    id: 1,
    subCatId: 1,
    name: "Televisies",
    price: 1200,
    rating: 4.3,
    quantity: 10,
    sell: false,
    img: require("../assets/categoryItems/c1.jpeg"),
    description: "good dmsof dmslkmfs fmoksdmfsd",
  },
  {
    id: 2,
    subCatId: 1,
    name: "Televisie accessoires",
    price: 1200,
    rating: 4.3,
    quantity: 10,
    sell: false,
    description: "good dmsof dmslkmfs fmoksdmfsd",
    img: require("../assets/categoryItems/c2.jpeg"),
  },
  {
    id: 3,
    subCatId: 1,
    name: "Home cinema",
    price: 1200,
    rating: 4.3,
    quantity: 10,
    sell: false,
    description: "good dmsof dmslkmfs fmoksdmfsd",
    img: require("../assets/categoryItems/c3.jpeg"),
  },
  {
    id: 4,
    subCatId: 1,
    name: "Speakers",
    price: 1200,
    rating: 4.3,
    quantity: 10,
    sell: false,
    description: "good dmsof dmslkmfs fmoksdmfsd",
    img: require("../assets/categoryItems/c4.jpeg"),
  },

  {
    id: 5,
    subCatId: 2,
    name: "Televisies",
    price: 1200,
    rating: 4.3,
    quantity: 10,
    sell: false,
    description: "good dmsof dmslkmfs fmoksdmfsd",
    img: require("../assets/categoryItems/c5.jpeg"),
  },
  {
    id: 6,
    subCatId: 2,
    name: "Televisie accessoires",
    price: 1200,
    rating: 4.3,
    quantity: 10,
    sell: false,
    description: "good dmsof dmslkmfs fmoksdmfsd",
    img: require("../assets/categoryItems/c6.jpeg"),
  },
  {
    id: 7,
    subCatId: 2,
    name: "Home cinema",
    price: 1200,
    rating: 4.3,
    quantity: 10,
    sell: false,
    description: "good dmsof dmslkmfs fmoksdmfsd",
    img: require("../assets/categoryItems/c7.jpeg"),
  },
  {
    id: 8,
    subCatId: 2,
    name: "Speakers",
    price: 1200,
    rating: 4.3,
    quantity: 10,
    sell: false,
    description: "good dmsof dmslkmfs fmoksdmfsd",
    img: require("../assets/categoryItems/c8.jpeg"),
  },

  {
    id: 9,
    subCatId: 3,
    name: "Televisies",
    price: 1200,
    rating: 4.3,
    quantity: 10,
    sell: false,
    description: "good dmsof dmslkmfs fmoksdmfsd",
    img: require("../assets/categoryItems/c13.jpeg"),
  },
  {
    id: 10,
    subCatId: 3,
    name: "Televisie accessoires",
    price: 1200,
    rating: 4.3,
    quantity: 10,
    sell: false,
    description: "good dmsof dmslkmfs fmoksdmfsd",
    img: require("../assets/categoryItems/c9.png"),
  },
  {
    id: 11,
    subCatId: 3,
    name: "Home cinema",
    price: 1200,
    rating: 4.3,
    quantity: 10,
    sell: false,
    description: "good dmsof dmslkmfs fmoksdmfsd",
    img: require("../assets/categoryItems/c11.jpeg"),
  },
  {
    id: 12,
    subCatId: 3,
    name: "Speakers",
    price: 1200,
    rating: 4.3,
    quantity: 10,
    sell: false,
    description: "good dmsof dmslkmfs fmoksdmfsd",
    img: require("../assets/categoryItems/c12.jpeg"),
  },
];

export const userLoginCredential = [
  { id: 1, username: "rajesh", password: "123456", active: false },
  { id: 2, username: "admin", password: "123456", active: false },
  { id: 3, username: "rakesh", password: "123456", active: false },
];
